// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8Fs56bz0coWttc-xuhsIw5hJKrJD8LnU',
    appId: '1:448470896814:web:4d7ab73c0696a5c868dd3f',
    databaseURL: 'https://crumbs-24265-default-rtdb.firebaseio.com/',
    messagingSenderId: '448470896814',
    projectId: 'crumbs-24265',
    authDomain: 'crumbs-24265.firebaseapp.com',
    storageBucket: 'crumbs-24265.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvXdfcLtuxwt5uDa47bkGyq-ss9Ik9C6s',
    appId: '1:448470896814:android:e00093aa5533034f68dd3f',
    databaseURL: 'https://crumbs-24265-default-rtdb.firebaseio.com/',
    messagingSenderId: '448470896814',
    projectId: 'crumbs-24265',
    storageBucket: 'crumbs-24265.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOzpTydu7XYBvwnzCQZrIklSMpWGyiLbo',
    appId: '1:448470896814:ios:bb8a44da39d5a1c868dd3f',
    databaseURL: 'https://crumbs-24265-default-rtdb.firebaseio.com/',
    messagingSenderId: '448470896814',
    projectId: 'crumbs-24265',
    storageBucket: 'crumbs-24265.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8Fs56bz0coWttc-xuhsIw5hJKrJD8LnU',
    appId: '1:448470896814:web:518d8c4c29d19c8a68dd3f',
    databaseURL: 'https://crumbs-24265-default-rtdb.firebaseio.com/',
    messagingSenderId: '448470896814',
    projectId: 'crumbs-24265',
    authDomain: 'crumbs-24265.firebaseapp.com',
    storageBucket: 'crumbs-24265.firebasestorage.app',
  );
}
